#server:
#    port:80
#    servlet:
#        context-path: /springboot

spring:
    profiles:
        # 区分不同环境下配置文件
        active: dev

    thymeleaf:
        #开发配置为false,避免修改模板还要重启服务器
        cache: false

    servlet:
        multipart:
            # 单个文件限制
            max-file-size: 300MB
            # 最大请求文件限制
            max-request-size: 500MB

#加密密钥
jasypt:
    encryptor:
        password: 2BTRS4Q6cmDsXOvquQq0qmjWtqvKnHEW
